### ISSUE TITLE
Must specify userName when calling with non-User credentials

### ISSUE THREAD

**Issue by llange** [codenize-tools/miam#17]
On some resources I have this error on update / delete.

I'm sure that it happens for policies - maybe some others but I have no example right now.

It seems to come from https://github.com/winebarrel/miam/blob/v0.2.4/lib/miam/driver.rb#L410 (for updates) where it tries to construct the ARN for the policy.

The ARN is constructed here https://github.com/winebarrel/miam/blob/v0.2.4/lib/miam/driver.rb#L463 with the user name.
(However, the ARN for a policy has no user name in it - but the account ID)

When it tries to fetch the current user, it fails - and then cannot construct the request.

However I'm pretty sure the resulting ARN won't identify the policy as it needs the account ID.

**Comment by yayugu** [comment]
STS GetCallerIdentity is better API to get account ID.
http://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html

https://github.com/gree/subiam/commit/9dc90871642d31696f1ffd918c6268a775119491

**Comment by llange** [comment]
@yayugu 's patch works fine.

Please merge it.

**Comment by winebarrel** [comment]
@llange I am sorry for the late reply. 🙇 
I merged your commit and released v0.2.4.beta9. 

@yayugu Thanks for your comment.

**Comment by llange** [comment]
I'm so late, sorry, but after near one year I'm closing this issue. Thanks !
