### ISSUE TITLE
JSON split file properly but call only IAMfile

### ISSUE THREAD

**Issue by jewelnuruddin** [codenize-tools/miam#28]
When I execute the following command, its properly create IAMfile and all others available json file 

$miam -e --split-more --format=json -o IAMfile
<pre>
|-- IAMfile
|-- groups
|   |-- Admin.iam.json
|   |-- development.iam.json
|-- policies
|   |-- Force_MFA.iam.json
|   `-- rds_read.iam.json
|-- roles
|   |-- XXX1_Role.iam.json
|   |-- XXX2_Role.iam.json
`-- users
    |-- XY.iam.json
    |-- YZ.iam.json

</pre>

Here If I want to manage files separately, for example I want to create a group, so
I edit like
$cd groups
$vim testgroup.iam.json

```
{
  "users": {
  },
  "groups": {
    "testgroup": {
      "path": "/",
      "policies": {
      },
      "attached_managed_policies": [
        "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      ]
    }
  },
  "roles": {
  },
  "instance_profiles": {
  },
  "policies": {
  }
}

```
 
$miam -a --format=json
No change
It alwasy give me No change, 

but if I edit/update IAMfile
$vim IAMfile

```
    "testgroup": {
      "path": "/",
      "policies": {
      },
      "attached_managed_policies": [
        "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      ]
    },
```

and execute 
$miam -a --format=json

<pre>

Create Group `testgroup`
Update Group `testgroup`
  attach policies=arn:aws:iam::aws:policy/AmazonS3FullAccess
</pre>

Its create group properly,

So what I would like to know that is JSON format work with only one file IAMfile ?
Or do I missing something ?

On the other hand it works perfectly on the DSL format, I can add edit/add/update simply anything in individual file and it works fine.

**Comment by limitusus** [comment]
Could not reproduce.

In my environment `IAMfile` was not created with `miam -e --split-more --format=json -o IAMfile`.
I checked the code but could not find code to create `IAMfile` with these options.
Didn't you create `IAMfile` without `--split-more` option?

As JSON has no semantics for including other files, a file kind of 'root' (`IAMfile` in Ruby DSL format) I think cannot exist.

It may be more user-friendly by causing error when `--split` or `--split-more` and `--format=json` at the same time, but the current behaviour itself seems correct.

**Comment by jewelnuruddin** [comment]
Thank for the feedback and make me clear,
yes to create one file like IAMfile, it need to run  without --split-more option.
