### ISSUE TITLE
Please release 0.2.4; currently default miam from rubygem is broken

### ISSUE THREAD

**Issue by Yuki-Inoue** [codenize-tools/miam#37]
Currently, when you `gem install miam` without the `--pre` option, the miam commands results in:

```
[ERROR] uninitialized constant Aws::IAM                                                   
Did you mean?  Miam    
```

Reason is the latest release version (0.2.3) does not have aws-sdk-core constraint of `< 3`, which results in version 3.x.x installed, which breaks everything.

To avoid this, I could use the prereleased version (`>= 0.2.4.beta14`), but I think this is not a good situation.

**Comment by limitusus** [comment]
Finally it's released https://github.com/codenize-tools/miam/releases/tag/v0.2.4
